-- The source catalog: where content comes from, never the content itself. Documents stay in the
-- search index, which remains their only durable copy.
--
-- Keys are UUIDv7, generated by Hibernate. Time ordered, so inserts land at the end of the index
-- instead of scattering across it the way random v4 keys do.

create table project (
    id           uuid        primary key,
    name         text        not null,
    version_rule jsonb,
    created_at   timestamptz not null,
    updated_at   timestamptz not null,

    -- The name is what list_projects hands out and search_docs is called with. Two projects of
    -- that name would make the MCP contract ambiguous.
    constraint project_name_unique unique (name)
);

create table source_system (
    id              uuid        primary key,
    name            text        not null,
    type            text        not null,
    url             text        not null,
    credentials_ref text,
    enabled         boolean     not null default true,
    created_at      timestamptz not null,
    updated_at      timestamptz not null,

    constraint source_system_name_unique unique (name),

    -- Mirrors SourceType, minus LOCAL: the local tree is configuration, not a remote system.
    -- Hibernate's schema validation does not check constraints like this one, so a new enum
    -- constant without a migration would only fail on the first insert - see
    -- SourceTypeConstraintTest.
    constraint source_system_type_check check (type in ('maven', 'git', 'wiki', 'http'))
);

create table content_source (
    id         uuid        primary key,
    project_id uuid        not null references project (id) on delete cascade,
    system_id  uuid                 references source_system (id) on delete restrict,
    type       text        not null,
    config     jsonb       not null,
    enabled    boolean     not null default true,
    refresh    text,
    created_at timestamptz not null,
    updated_at timestamptz not null,

    constraint content_source_type_check
        check (type in ('maven', 'git', 'wiki', 'http', 'local')),

    -- Local sources read from docs.data-dir and have no remote system; every other kind must name
    -- one. Written as an equivalence so both mistakes are caught, not just the missing system.
    constraint content_source_system_required
        check ((type = 'local') = (system_id is null)),

    -- The same coordinates must not hang off one project twice: everything would be fetched
    -- twice, and the deletion pass would count wrong. This works because jsonb normalises key
    -- order and whitespace - over text the same coordinates written differently would be two
    -- rows. Should config ever grow past roughly 2.7 kB, the btree index behind this constraint
    -- refuses the row; a generated hash column would be the way out.
    constraint content_source_coordinates_unique unique (project_id, system_id, config)
);

-- The constraint above leaves local sources uncovered, because Postgres treats null system_id
-- values as distinct from each other. NULLS NOT DISTINCT would say this in one word but needs
-- Postgres 15, so a partial index closes the gap without a version requirement.
create unique index content_source_local_unique
    on content_source (project_id, config)
    where system_id is null;

-- Postgres does not index foreign keys by itself, and every scan starts by asking for the sources
-- of one project.
create index content_source_project_idx on content_source (project_id);
